import './js/header-menu';
import './js/markup-books';
import './js/axios-get';
import './js/get-top-books';
import './js/modal';
import './js/animation';
import './js/auth-for-all-pages';
import './js/footer.js';
import './js/scroll-up.js';
import './js/onFondsBtnClick.js';
import './js/renderCategories.js';
import './js/toggleTheme.js';
import './js/createFoundsMarcup';
import './js/createCategoryMarcup.js';
import './js/seeMore';
import './js/scroll-funds'