import './js/shop-list';
import './js/header-menu';
import './js/toggleTheme.js';
import './js/createFoundsMarcup';
import './js/orderModal.js';
import './js/auth-for-all-pages';
import './js/google';
import './js/footer'
import './js/auth-for-all-pages';
import './js/scroll-funds';
import './js/loader';
import './js/loadBasket';